builds:
  - main: ./cmd/helmpush
    binary: ./bin/helmpush
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
  - id: release
    format: tar.gz
    files:
      - LICENSE
      - plugin.yaml
